# Generated by Django 6.0.3 on 2026-05-06 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStrengthWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strongest_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('weakest_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('average_quiz_score', models.FloatField(default=0)),
                ('learning_speed', models.CharField(choices=[('slow', 'Slow'), ('average', 'Average'), ('fast', 'Fast')], default='average', max_length=20)),
                ('engagement_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('recommended_resources', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strengths_weaknesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_strength_weakness',
            },
        ),
        migrations.CreateModel(
            name='ClassAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('median_score', models.FloatField(default=0)),
                ('pass_rate', models.FloatField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('most_challenging_topic', models.CharField(blank=True, max_length=255)),
                ('least_challenging_topic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_analytics', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Class Analytics',
                'db_table': 'class_analytics',
                'unique_together': {('course',)},
            },
        ),
        migrations.CreateModel(
            name='PerformanceHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('difficulty_score', models.FloatField(default=0)),
                ('common_mistakes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='quizzes.question')),
            ],
            options={
                'db_table': 'performance_heatmaps',
                'unique_together': {('question',)},
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0)),
                ('average_completion_rate', models.FloatField(default=0)),
                ('students_passed', models.IntegerField(default=0)),
                ('students_failed', models.IntegerField(default=0)),
                ('most_common_mistakes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='courses.course')),
            ],
            options={
                'db_table': 'performance_metrics',
                'unique_together': {('course',)},
            },
        ),
    ]
